-- REF: https://github.com/LunarVim/Neovim-from-scratch

require "user.options"
require "user.keymaps"
require "user.reload"
require "user.plugins"
require "user.colorscheme"
-- require "user.lsp"
require "user.telescope"
require "user.cocnew"
require "user.autopairs"
require "user.treesitter"
require "user.comment"
-- require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
-- require "user.indentline"
-- require "user.alpha"
require "user.whichkey"
require "user.trouble"
require "user.sessions"
require "user.markdown"
require "user.autocommands"
