link:
	ln -sf /Users/lzx/code/dotfiles/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
	ln -sf /Users/lzx/code/dotfiles/vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json
