- name: Install swaywm required packages
  become: yes
  pacman:
    state: present
    name:
      - sway
      - waybar
      - swaylock
      - swayidle
      - mako
      - brightnessctl
      - rofi
      - grim
      - slurp
      - wallutils
      - termite
      - termite-terminfo
      - alacritty
      - powerline-fonts
      - ttf-font-awesome
      - ttf-monaco
      - wqy-microhei
      - wqy-zenhei
      - wqy-bitmapfont
      - noto-fonts-emoji
      - pamixer
      - pnmixer
      - pavucontrol
      - alsa-utils
      - bluez
      - bluez-utils
      - blueman
      - pulseaudio-bluetooth
      - network-manager-applet
      - acpilight
      - ydcv
      - wl-clipboard
      - redshift
      - gammastep
      # - wdisplays-git
      - network-manager-applet
      - libappindicator-gtk3
      - swappy
      # - wofi-hg


- name: Copy config/sway
  synchronize:
    src: sway
    dest: "{{ config_path }}"

- name: Copy config/swappy
  synchronize:
    src: swappy
    dest: "{{ config_path }}"

- name: Install gnome required packages
  become: yes
  pacman:
    state: present
    name:
    - gnome-extra
    - gdm

- name: Copy /etc/environment
  become: yes
  copy:
    src: etc/environment
    dest: /etc/environment
    mode: '0644'
