- name: Install rofi required packages
  become: yes
  pacman:
    state: present
    name:
    #- rofi
    - rofi-lbonn-wayland-git

- name: Sync config/rofi
  synchronize:
    src: rofi
    dest: "{{ config_path }}"
