#!/bin/bash

laptop="eDP-1"
external="DP-2"
external1="HDMI-A-1"

mode=$1

if [[ $mode == 3 ]]; then
    swaymsg output $external pos 0 0 res 2560x1440
    swaymsg output $laptop pos 2560 360 res 1920x1080
    swaymsg output $external1 enable
    swaymsg output $external1 pos 640 1440 res 1920x1080
elif [[ $mode == "3.1" ]]; then
    swaymsg output $laptop pos   600 360 res 1920x1080
    swaymsg output $external pos 2520 0 res 2560x1440
    swaymsg output $external1 enable
    swaymsg output $external1 pos 2520 1440 res 1920x1080
elif [[ $mode == "3.2" ]]; then
    swaymsg output $laptop pos   3017 617 res 2560x1440
    swaymsg output $external pos 4480 0 res 2560x1440
    swaymsg output $external1 enable
    swaymsg output $external1 pos 4480 1440 res 1920x1080
elif [[ $mode == "3-right" ]]; then
    swaymsg output $laptop pos   2560 617 res 2560x1440
    swaymsg output $external pos 0 0 res 2560x1440
    swaymsg output $external1 enable
    swaymsg output $external1 pos 640 1440 res 1920x1080
elif [[ $mode == "4k" ]]; then
    swaymsg output $external enable scale 2
    swaymsg output $laptop pos 0 1080 res 1920x1080
    swaymsg output $external pos 0 0 res 3840x2160
else
    swaymsg output $external pos 0 0 res 2560x1440
    swaymsg output $external1 disable
    swaymsg output $laptop pos 0 1440 res 1920x1080
fi

# external top of laptop
#swaymsg output $external pos 0 0 res 1920x1080
#swaymsg output $external pos 0 0 res 2560x1440
#swaymsg output $laptop pos 0 1440 res 1920x1080
#swaymsg output $laptop pos 2560 360 res 1920x1080
#swaymsg output $external1 pos 640 1440 res 1920x1080
